### ISSUE TITLE
Support for ESP8266

### ISSUE THREAD

**Issue by Shdwdrgn** [stm32duino/VL53L4CD#7]
> request for member 'begin' in 'vl53l4cd', which is of non-class type 'VL53L4CD()'

I'm trying to compile the sample code on a D1 Mini board, but this appears to be a problem within the driver code?  I have reduced the code to the minimal amount which still gets the same failure (I have to define the I2C pins and I saw elsewhere that vl53l4cd() could be started without any parameters since I'm only using the four I2C lines from the sensor).

```c++
#include <Wire.h>
#include <vl53l4cd_class.h>

VL53L4CD vl53l4cd();

void setup() {
  Wire.begin(D2, D1);
  vl53l4cd.begin();
}

void loop() {
}
```

Any suggestions on where I need to go from here?

**Comment by Shdwdrgn** [comment]
After looking through vl53l4cd_class.h I realized it DOES require parameters, apparently even the analog port despite not being used.  After correcting that with the line `VL53L4CD vl53l4cd(&Wire, 0);` I then ran into another problem.  This driver assumes the device will be on I2C address 0x52 when in fact the VL53L4CD uses address 0x29.  I updated my code with `vl53l4cd.InitSensor(0x29);` and everything is working now, but it might be worthwhile to update either the driver or the examples.

**Comment by cparata** [comment]
Hello @Shdwdrgn ,
in fact VL53L4CD constructor requires I2C instance and shutdown pin as input parameters. If the shutdown pin is not connected to the MCU, you can pass 0 or -1 as second parameter as you did and everything should be fine. Regarding the default I2C address, actually 0x52 should be the default one from the datasheet. 0x29 is 0x52 right-shifted by 1. If you call `vl53l4cd.InitSensor(0x29);` basically you are assigning 0x29 as new I2C address. If you check in the source code inside the platform.cpp file, you find that in the I2C transactions we use `dev_i2c->beginTransmission((uint8_t)((DeviceAddr >> 1) & 0x7F));` and `dev_i2c->requestFrom(((uint8_t)((DeviceAddr >> 1) & 0x7F)), current_read_size);`. This is the reason why the default I2C address is 0x52.
Best Regards,
Carlo

**Comment by Shdwdrgn** [comment]
That's odd about the address, perhaps the manufacturer of the board I have is changing it.  After discovering my error with the first bit of code I still wasn't able to communicate with the chip so I ran an I2C scanner code to see if I had this board wired correctly, and that's what told me that it was found at 0x29.  I also found that the board Adafruit sells uses the same 0x29 address so perhaps the board I'm using just copied that?  Oh well, it seems to be working fine now.

One more question regarding the driver... Other I2C devices that I have used will return true/false from the begin() function which indicates if the device is actually detected.  Could that be added into this driver as well?  A very basic technique that I'm using in my code right now is this:

```
Wire.beginTransmission(VL53L4CD_ADDRESS);
uint8_t error = Wire.endTransmission();
if (error == 0) { //device detected! }
```

I don't know if there is a more elegant way of doing this but it tells me that the device was found before I attempt to initialize it.  I run the same code on a number of different devices which all have different sensors attached to them so in setup I have to check for each type of sensor to see what is available.

**Comment by cparata** [comment]
Hello @Shdwdrgn ,
the call to `vl53l4cd.InitSensor(0x29);` changes physically the I2C address used by the sensor in 0x29 and when you call this function you are using 0x52 as I2C default address. Did you try to call  `vl53l4cd.InitSensor();` without any parameter to see if it continue to works also with 0x52 address? Regarding your proposal about the begin(), I prefer to manage the check at the application level as you did because this library is done to change the I2C address if you want (using the vl53l4cd.InitSensor), so I would not put I2C calls inside the begin, before calling the vl53l4cd.InitSensor.
Best Regards,
Carlo

**Comment by cparata** [comment]
Hello @Shdwdrgn ,
I did not receive any feedback about the last post. Could we close this ticket?
Best Regards,
Carlo

**Comment by Shdwdrgn** [comment]
I finally had a chance to test this again calling InitSensor without an address, and I find that both the simple test script and my own much larger code is crashing unless I do include the address.  I'm posting the stack dump below in case this is of use to you, but at the moment it appears I cannot use this driver unless I specify the device address.

```
14:40:35.690 -> Soft WDT reset
14:40:35.690 -> 
14:40:35.690 -> >>>stack>>>
14:40:35.690 -> 
14:40:35.690 -> ctx: cont
14:40:35.690 -> sp: 3ffffd00 end: 3fffffc0 offset: 01a0
14:40:35.690 -> 3ffffea0:  3ffee578 00000001 3ffee578 40202c24  
14:40:35.690 -> 3ffffeb0:  3ffee578 00000148 00000006 40202ce8  
14:40:35.723 -> 3ffffec0:  00000000 00000004 3ffee578 40202dd2  
14:40:35.723 -> 3ffffed0:  3ffee3af 00000029 feefeffe feefeffe  
14:40:35.723 -> 3ffffee0:  feefef0f feefeffe feefeffe 0000010f  
14:40:35.723 -> 3ffffef0:  00000002 00000002 3ffee3ad 4020306c  
14:40:35.723 -> 3fffff00:  40203ac9 feefeffe feefeffe 4020144c  
14:40:35.723 -> 3fffff10:  00000002 00000002 3ffee38c 402014da  
14:40:35.723 -> 3fffff20:  007a0f01 7115f27e 00004900 00000000  
14:40:35.756 -> 3fffff30:  00000029 3fffff60 00000001 00000000  
14:40:35.756 -> 3fffff40:  3ffe88b0 3ffee640 0000000a 3ffee538  
14:40:35.756 -> 3fffff50:  3fffdad0 00000000 3fffff90 402015cd  
14:40:35.756 -> 3fffff60:  40200000 0000000a 3ffee538 402031be  
14:40:35.756 -> 3fffff70:  3fffdad0 00000000 3ffee38c 4020174d  
14:40:35.756 -> 3fffff80:  3fffdad0 00000000 3ffee38c 4020113a  
14:40:35.756 -> 3fffff90:  feefeffe feefeffe feefeffe feefeffe  
14:40:35.789 -> 3fffffa0:  feefeffe feefeffe 3ffee4f8 4020258c  
14:40:35.789 -> 3fffffb0:  feefeffe feefeffe 3ffe84e8 40100e75  
14:40:35.789 -> <<<stack<<<
```

**Comment by cparata** [comment]
This is really strange. Unfortunately, I do not have an ESP8266 based board to make some tests on my side. Is the VL53L4CD the only device that you have on the I2C bus?

**Comment by Shdwdrgn** [comment]
On this particular setup I also have an SHT30 connected, however the code is not initializing or using that device.

One thing I still don't understand -- why do you bit-shift the I2C address?  It seems like that would mean the code itself is changing what address the device uses, rather than using the actual address that it is programmed with?

**Comment by cparata** [comment]
Hi @Shdwdrgn ,
The I2C address in the [beginTransmission()](https://www.arduino.cc/reference/en/language/functions/communication/wire/begintransmission/) and in the [requestFrom()](https://www.arduino.cc/reference/en/language/functions/communication/wire/requestfrom/) is in 7-bit format but the slave address of the VL53L4CD component is in 8-bit format. So, as explained [here](https://www.totalphase.com/support/articles/200349176-7-bit-8-bit-and-10-bit-I2C-Slave-Addressing), we need to take only the 7 most significant bits when we pass the slave address to the Wire APIs.
Best Regards,
Carlo

**Comment by fpistm** [comment]
Any update on this ?

**Comment by Shdwdrgn** [comment]
I wanted to provide some further info, although I'm not sure if it belongs here or in a new ticket?  I picked up this sensor to use as a snow depth sensor, and was able to add it to my weather station earlier this month.  Unfortunately it did NOT get a reading off the snow but I have not had a chance to conduct further testing to determine if that had to do with the angle of the sensor or a problem with the reflectivity of the snow itself.

In the meantime, two issues came up.  The first is that when the sensor is plugged in and being read, the weather station is locking up and requires rebooting every couple days.  Using the same code with the sensor unplugged (the library is still installed but no calls are made to read the sensor) the station runs continuously without any errors.

The second issue is that calls to the VL53L4 module appear to prevent an AS5600 (a magnetic angle sensor on address 0x36) from working.  Including these two sensors, I have a total of five I2C devices connected, none of which operate at high speed (calls are generally only made once every 5 minutes to each device).  I also plan to try and investigate this seeming conflict between these two devices, but I wanted to mention it so you are aware.

So currently I have removed the VL53L4 from my weather station and have it back on my workbench again.  When I get a chance I'll set up an ESP8266 to read the device for multiple days without any other I2C devices attached, and see what happens.  I also have more of the AS5600 sensors on hand, so after I check for any long-term problems I'll try hooking up another of these angle sensors and see if I can figure out why the two devices don't seem to work together.  I might have some time to get it set up over the weekend or next week.

**Comment by fpistm** [comment]
Hi @Shdwdrgn 
any update on this else we will close this issue.

**Comment by fpistm** [comment]
Closed as no feedback from OP.

**Comment by Shdwdrgn** [comment]
Sorry for the slow response.  So my current status on all of this...  I was never able to get the device to work without specifying the I2C address, but it seems to work just fine when I specify 0x29 to start it up.

The lockups appear to have gone away but I don't know what was changed.  I have an ESP8266 on my desk that has been running for months at a time without any further issues.

I never got back to testing with the AS5600 again, although I do have an extra module here to test with on the bench.  The VL53L4 modules appears to be working just fine with all other I2C devices (although I still cannot get any solid measurements off of water or ice surfaces, so it probably will not work for measuring snow depth).

I would say go ahead and leave this ticket closed.  If I run into any new, specific issues I will start a new ticket.
